# from https://github.com/docker/build-push-action#git-context

name: "Publish to Docker Hub (tag)"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Retrieve tag name
        run: |
          TAG_NAME="${GITHUB_REF#refs/*/}"
          echo "RELEASE_VERSION=${TAG_NAME:1}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "utybo/epita-c-cpp:latest,utybo/epita-c-cpp:${{ env.RELEASE_VERSION }}"
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
